CREATE TABLE IF NOT EXISTS `gs_billing` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `target_citizenid` VARCHAR(64) NOT NULL,
    `target_name` VARCHAR(128) NOT NULL,
    `issuer_citizenid` VARCHAR(64) NOT NULL,
    `issuer_name` VARCHAR(128) NOT NULL,
    `issuer_job` VARCHAR(64) NOT NULL,
    `issuer_job_label` VARCHAR(128) NOT NULL,
    `society` VARCHAR(64) NOT NULL,
    `label` VARCHAR(128) NOT NULL,
    `description` VARCHAR(255) DEFAULT NULL,
    `amount` INT NOT NULL DEFAULT 0,
    `amount_due` INT NOT NULL DEFAULT 0,
    `late_fee_percent` FLOAT NOT NULL DEFAULT 3,
    `due_at` DATETIME NOT NULL,
    `status` ENUM('pending', 'paid', 'cancelled') NOT NULL DEFAULT 'pending',
    `paid_at` DATETIME DEFAULT NULL,
    `cancelled_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_target_citizenid` (`target_citizenid`),
    INDEX `idx_issuer_citizenid` (`issuer_citizenid`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;